const http=require("http"),fs=require("fs"),path=require("path"),{execFile}=require("child_process");
const ROOT=path.resolve(__dirname,".."),UI=path.join(__dirname,"public"),HOST="127.0.0.1",PORT=Number(process.env.SITE_STUDIO_PORT||4174),MAX=100*1024*1024;
const MIME={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png",".webp":"image/webp"};
const DATA=path.join(ROOT,"public","data","content.json"),THEMES=path.join(ROOT,"public","data","themes.json"),ASSETS=path.join(ROOT,"public","assets","uploads");
function json(res,status,data){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(data))}
function readBody(req){return new Promise((resolve,reject)=>{let size=0,chunks=[];req.on("data",chunk=>{size+=chunk.length;if(size>MAX){reject(new Error("Upload too large"));req.destroy()}else chunks.push(chunk)});req.on("end",()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString("utf8")||"{}"))}catch{reject(new Error("Invalid request"))}});req.on("error",reject)})}
function clean(value,max=100000){return String(value??"").replace(/\0/g,"").slice(0,max).trim()}
function slug(value){return clean(value,120).normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g,"-").replace(/^-|-$/g,"").slice(0,60)||Date.now().toString(36)}
function saveImage(file,prefix){const match=String(file?.dataUrl||"").match(/^data:image\/(jpeg|png|webp);base64,([\s\S]+)$/);if(!match)throw new Error("Only JPG, PNG, or WebP images are accepted");fs.mkdirSync(ASSETS,{recursive:true});const ext=match[1]==="jpeg"?"jpg":match[1],name=`${prefix}-${Date.now().toString(36)}.${ext}`;fs.writeFileSync(path.join(ASSETS,name),Buffer.from(match[2],"base64"));return `assets/uploads/${name}`}
function uploadedFiles(){if(!fs.existsSync(ASSETS))return[];return fs.readdirSync(ASSETS).filter(name=>fs.statSync(path.join(ASSETS,name)).isFile()).map(name=>`public/assets/uploads/${name}`)}
function git(args){return new Promise((resolve,reject)=>execFile("git",args,{cwd:ROOT,windowsHide:true,maxBuffer:4e6},(error,stdout,stderr)=>error?reject(new Error((stderr||stdout||error.message).trim())):resolve(stdout.trim())))}
async function status(){return{branch:await git(["branch","--show-current"]),files:(await git(["status","--short"])).split(/\r?\n/).filter(Boolean),last:await git(["log","-1","--pretty=%h %s"])} }
function publicFile(res,base,relative){const target=path.resolve(base,relative);if(!target.startsWith(base)||!fs.existsSync(target)||!fs.statSync(target).isFile()){res.writeHead(404);res.end("Not found");return}res.writeHead(200,{"Content-Type":MIME[path.extname(target).toLowerCase()]||"application/octet-stream","Cache-Control":"no-store"});fs.createReadStream(target).pipe(res)}
async function api(req,res,url){if(req.method==="GET"&&url.pathname==="/api/state"){json(res,200,{content:JSON.parse(fs.readFileSync(DATA,"utf8")),themes:JSON.parse(fs.readFileSync(THEMES,"utf8")),git:await status()});return}if(req.method!=="POST"){json(res,405,{error:"Method not allowed"});return}const body=await readBody(req),content=JSON.parse(fs.readFileSync(DATA,"utf8"));
 if(url.pathname==="/api/save"){if(!body.content?.profile?.name)throw new Error("Profile name is required");fs.writeFileSync(DATA,JSON.stringify(body.content,null,2)+"\n","utf8");json(res,200,{ok:true});return}
 if(url.pathname==="/api/upload"){const result=saveImage(body.file,slug(body.prefix||"image"));json(res,200,{ok:true,path:result});return}
 if(url.pathname==="/api/publish"){const current=await status();if(current.branch!=="main")throw new Error(`Switch to main before publishing (current: ${current.branch})`);const publishPaths=["public/data/content.json",...uploadedFiles()];await git(["add","--",...publishPaths]);const staged=await git(["diff","--cached","--name-only","--",...publishPaths]);if(!staged)throw new Error("No Studio changes to publish");await git(["commit","--only","-m",clean(body.message,180)||"Update personal site content","--",...publishPaths]);await git(["push","origin","main"]);json(res,200,{ok:true,git:await status()});return}
 json(res,404,{error:"Unknown endpoint"})}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${HOST}:${PORT}`);try{if(url.pathname.startsWith("/api/"))await api(req,res,url);else if(url.pathname.startsWith("/preview/"))publicFile(res,path.join(ROOT,"public"),url.pathname.replace("/preview/","")||"index.html");else publicFile(res,UI,url.pathname==="/"?"index.html":url.pathname.slice(1))}catch(error){json(res,400,{error:error.message})}});
server.on("error",error=>{console.error(error.code==="EADDRINUSE"?`Port ${PORT} is already in use. Studio may already be running.`:error.message);process.exit(1)});
server.listen(PORT,HOST,()=>{const url=`http://${HOST}:${PORT}`;console.log(`Personal Site Studio: ${url}`);console.log("Keep this window open. Press Ctrl+C to stop.");if(process.platform==="win32"&&process.env.SITE_STUDIO_NO_OPEN!=="1")execFile("cmd",["/c","start","",url],{windowsHide:true},()=>{})});
